bucket_name = "tf13.douglasnaphas.com-origin"
cert_domain = "douglasnaphas.com"
domain_name = "tf13.douglasnaphas.com"
ci_user_arn = "arn:aws:iam::050877257577:user/admin_douglas_naphas"
zone_name   = "douglasnaphas.com"
repo_owner = "douglasnaphas"
# repo_name = "tf13-site-01"
repo_branch = "master"
